# Regresión lineal en Python

## Paquete scikit-learn para regresión lineal y la selección de rasgos

In [12]:
# Importación de librerías
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv("Advertising.csv")

In [6]:
# Nombre de las columnas
feature_cols = ["TV", "Radio", "Newspaper"]

In [7]:
# Variables predictoras
x = data[feature_cols]
# Variables a ser predecidas
y = data["Sales"]

In [9]:
# Modelo lineal
estimator = SVR(kernel = "linear")
selector = RFE(estimator, 2, step = 1)
selector = selector.fit(x,y)

In [10]:
selector.support_

array([ True,  True, False])

In [11]:
# ranking de variables
selector.ranking_

array([1, 1, 2])

In [13]:
x_pred = x[["TV", "Radio"]]

In [14]:
lm = LinearRegression()
lm.fit(x_pred,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [15]:
lm.intercept_

2.921099912405138

In [16]:
lm.coef_

array([0.04575482, 0.18799423])